import {
  ADJACENT_PROPS,
  BORDER_PROPS,
  COLOR_PROPS,
  COMMONS_COMPONENT_PROPS,
  DENSITY_PROPS, DIMENSIONS_PROPS, ELEVATION_PROPS,
  MARGIN_PROPS,
  PADDING_PROPS,
  ROUNDED_PROPS,
  VALIDATION_PROPS,
  DIRECTION_PROPS
} from '@foxy/consts'

import { IInputProps } from '@foxy/interfaces'

export const INPUT_PROPS: IInputProps = {
  ...COMMONS_COMPONENT_PROPS,
  ...DENSITY_PROPS,
  ...PADDING_PROPS,
  ...MARGIN_PROPS,
  ...ROUNDED_PROPS,
  ...COLOR_PROPS,
  ...BORDER_PROPS,
  ...ELEVATION_PROPS,
  ...DIMENSIONS_PROPS,
  ...DIRECTION_PROPS,
  ...ADJACENT_PROPS,
  ...VALIDATION_PROPS,

  centerAffix: undefined,
  hideDetails: undefined,
  hideSpinButtons: undefined,
  hint: undefined,
  persistentHint: undefined,
  messages: undefined
}

export const BUBBLING_EVENTS = [
  'onAfterscriptexecute',
  'onAnimationcancel',
  'onAnimationend',
  'onAnimationiteration',
  'onAnimationstart',
  'onAuxclick',
  'onBeforeinput',
  'onBeforescriptexecute',
  'onChange',
  'onClick',
  'onCompositionend',
  'onCompositionstart',
  'onCompositionupdate',
  'onContextmenu',
  'onCopy',
  'onCut',
  'onDblclick',
  'onFocusin',
  'onFocusout',
  'onFullscreenchange',
  'onFullscreenerror',
  'onGesturechange',
  'onGestureend',
  'onGesturestart',
  'onGotpointercapture',
  'onInput',
  'onKeydown',
  'onKeypress',
  'onKeyup',
  'onLostpointercapture',
  'onMousedown',
  'onMousemove',
  'onMouseout',
  'onMouseover',
  'onMouseup',
  'onMousewheel',
  'onPaste',
  'onPointercancel',
  'onPointerdown',
  'onPointerenter',
  'onPointerleave',
  'onPointermove',
  'onPointerout',
  'onPointerover',
  'onPointerup',
  'onReset',
  'onSelect',
  'onSubmit',
  'onTouchcancel',
  'onTouchend',
  'onTouchmove',
  'onTouchstart',
  'onTransitioncancel',
  'onTransitionend',
  'onTransitionrun',
  'onTransitionstart',
  'onWheel',
]