export { default as FoxyIcon } from './FoxyIcon.vue'
export { default as FoxyClassIcon } from './FoxyClassIcon.vue'
export { default as FoxyComponentIcon } from './FoxyComponentIcon.vue'
export { default as FoxyLigatureIcon } from './FoxyLigatureIcon.vue'
export { default as FoxySvgIcon } from './FoxySvgIcon.vue'