export { default as FoxuiIcon } from './FoxuiIcon.vue'
export { default as FoxuiClassIcon } from './FoxuiClassIcon.vue'
export { default as FoxuiComponentIcon } from './FoxuiComponentIcon.vue'
export { default as FoxuiLigatureIcon } from './FoxuiLigatureIcon.vue'
export { default as FoxuiSvgIcon } from './FoxuiSvgIcon.vue'
