import {
  BORDER_PROPS,
  COLOR_PROPS,
  COMMONS_COMPONENT_PROPS,
  DENSITY_PROPS,
  DIMENSIONS_PROPS,
  ELEVATION_PROPS,
  LINK_PROPS,
  LOADER_PROPS,
  LOCATION_PROPS,
  MARGIN_PROPS,
  PADDING_PROPS,
  POSITION_PROPS,
  RIPPLE_PROPS,
  ROUNDED_PROPS,
  TAG_PROPS
} from '@foxy/consts'

import {
  IBorderProps,
  ICardProps,
  IColorProps,
  ICommonsComponentProps,
  IDensityProps,
  IDimensionProps,
  IElevationProps,
  ILinkProps,
  ILoaderProps,
  ILocationProps,
  IMarginProps,
  IPaddingProps,
  IPositionProps,
  IRippleProps,
  IRoundedProps,
  ITagProps
} from '@foxy/interfaces'

export const CARD_PROPS:ICardProps = {
  ...COMMONS_COMPONENT_PROPS as ICommonsComponentProps,
  ...TAG_PROPS as ITagProps,
  ...COLOR_PROPS as IColorProps,
  ...BORDER_PROPS as IBorderProps,
  ...PADDING_PROPS as IPaddingProps,
  ...MARGIN_PROPS as IMarginProps,
  ...DIMENSIONS_PROPS as IDimensionProps,
  ...DENSITY_PROPS as IDensityProps,
  ...ELEVATION_PROPS as IElevationProps,
  ...LOCATION_PROPS as ILocationProps,
  ...POSITION_PROPS as IPositionProps,
  ...ROUNDED_PROPS as IRoundedProps,
  ...LOADER_PROPS as ILoaderProps,
  ...LINK_PROPS as ILinkProps,
  ...RIPPLE_PROPS as IRippleProps,

  appendAvatar: undefined,
  appendIcon: undefined,
  disabled: undefined,
  flat: undefined,
  hover: undefined,
  image: undefined,
  link: undefined,
  prependAvatar: undefined,
  prependIcon: undefined,
  subtitle: undefined,
  text: undefined,
  title: undefined,
  type: undefined,
}