import {
  BORDER_PROPS,
  COLOR_PROPS,
  COMMONS_COMPONENT_PROPS,
  DENSITY_PROPS,
  DIMENSIONS_PROPS,
  ELEVATION_PROPS,
  LINK_PROPS,
  LOADER_PROPS,
  LOCATION_PROPS,
  MARGIN_PROPS,
  PADDING_PROPS,
  POSITION_PROPS,
  RIPPLE_PROPS,
  ROUNDED_PROPS,
  TAG_PROPS
} from '@foxy/consts'

import { ICardProps } from '@foxy/interfaces'

export const CARD_PROPS:ICardProps = {
  ...COMMONS_COMPONENT_PROPS,
  ...TAG_PROPS,
  ...COLOR_PROPS,
  ...BORDER_PROPS,
  ...PADDING_PROPS,
  ...MARGIN_PROPS,
  ...DIMENSIONS_PROPS,
  ...DENSITY_PROPS,
  ...ELEVATION_PROPS,
  ...LOCATION_PROPS,
  ...POSITION_PROPS,
  ...ROUNDED_PROPS,
  ...LOADER_PROPS,
  ...LINK_PROPS,
  ...RIPPLE_PROPS,

  appendAvatar: undefined,
  appendIcon: undefined,
  disabled: undefined,
  flat: undefined,
  hover: undefined,
  image: undefined,
  link: undefined,
  prependAvatar: undefined,
  prependIcon: undefined,
  subtitle: undefined,
  text: undefined,
  title: undefined,
  type: undefined,
}