export { default as FoxyDataTable } from './FoxyDataTable.vue'
export { default as FoxyDataTableHeaders } from './FoxyDataTableHeaders.vue'
export { default as FoxyDataTableHeadersCellMobile } from './FoxyDataTableHeadersCellMobile.vue'
export { default as FoxyDataTableHeadersCell } from './FoxyDataTableHeadersCell.vue'
export { default as FoxyDataTableHeaderCell } from './FoxyDataTableHeaderCell.vue'
export { default as FoxyDataTableColumnCell } from './FoxyDataTableColumnCell.vue'